import { test, expect } from "@playwright/test";
import { createRequire } from "module";
import fs from "fs/promises";
import path from "path";
const require = createRequire(import.meta.url);
const mongoose = require("../../../node_modules/mongoose"); const bcrypt = require("../../../node_modules/bcryptjs");
const User = require("../../../models/User"); const AuditLog = require("../../../models/AuditLog"); const AdminInvitation = require("../../../models/AdminInvitation");
require("../../../node_modules/dotenv").config({ path: path.resolve("..", ".env") });
const password = "AdminAccessTest123!"; const screenshots = "screenshots/admin-access-v1-1"; let admin; const invitationIds = []; const userIds = [];
test.use({ storageState: { cookies: [], origins: [] } });
test.beforeAll(async ({}, workerInfo) => { await fs.mkdir(screenshots, { recursive: true }); await mongoose.connect(process.env.MONGO_URI_TEST || process.env.MONGO_URI); admin = await User.create({ email: `admin-access-v11-${Date.now()}-${workerInfo.project.name}@aurapay.test`, password: await bcrypt.hash(password, 4), role: "super_admin", status: "verified", emailVerified: true }); userIds.push(admin._id); });
test.afterAll(async () => { await AuditLog.deleteMany({ $or: [{ admin: { $in: userIds } }, { targetId: { $in: [...userIds, ...invitationIds].map(String) } }] }); await AdminInvitation.deleteMany({ _id: { $in: invitationIds } }); await User.deleteMany({ _id: { $in: userIds } }); await mongoose.disconnect(); });
async function login(request) { const backend = process.env.AURAPAY_BACKEND_URL || "http://localhost:3000"; const response = await request.post(`${backend}/admin-auth/login`, { data: { email: admin.email, password } }); return (await response.json()).data; }
async function authenticate(page, request) { const data = await login(request); await page.goto("/"); await page.evaluate(({ token, user }) => { localStorage.setItem("adminToken", token); localStorage.setItem("adminUser", JSON.stringify(user)); }, { token: data.token, user: data.admin }); }
async function invite(request, suffix = "invite") { const backend = process.env.AURAPAY_BACKEND_URL || "http://localhost:3000"; const auth = await login(request); const response = await request.post(`${backend}/admin-auth/invitations`, { headers: { authorization: `Bearer ${auth.token}` }, data: { email: `admin-access-v11-${suffix}-${Date.now()}@aurapay.test`, role: "support_admin" } }); const body = await response.json(); invitationIds.push(body.data.invitation.id); return body.data; }

test("Staff Access leads to responsive Staff Sign In with generic errors", async ({ page }) => { await page.goto("/"); const link = page.getByRole("link", { name: "Staff Access" }); await expect(link).toBeVisible(); await link.click(); await expect(page.getByRole("heading", { name: "Staff sign in" })).toBeVisible(); await page.setViewportSize({ width: 1440, height: 900 }); await page.screenshot({ path: `${screenshots}/staff-login-desktop.png`, fullPage: true }); await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: `${screenshots}/staff-login-mobile.png`, fullPage: true }); await page.getByLabel("Email address").fill(admin.email); await page.locator('input[autocomplete="current-password"]').fill("wrong"); await page.getByRole("button", { name: "Sign in" }).click(); await expect(page.getByText("Unable to sign in with those credentials.")).toBeVisible(); await expect(page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).resolves.toBe(true); });

test("invitation password policy, confirmation, acceptance, and invalid state", async ({ page, request }) => { const pending = await invite(request, "accept"); const token = pending.developmentInviteLink.split("/").pop(); await page.setViewportSize({ width: 1440, height: 900 }); await page.goto(`/admin-invitation/${token}`); await expect(page.getByRole("heading", { name: "Accept invitation" })).toBeVisible(); await page.screenshot({ path: `${screenshots}/invitation-accept-desktop.png`, fullPage: true }); const submit = page.getByRole("button", { name: "Activate admin access" }); await page.getByLabel("New password").fill("short"); await expect(page.getByText("At least 10 characters")).toBeVisible(); await expect(submit).toBeDisabled(); await page.getByLabel("New password").fill("StrongInvite123"); await page.getByLabel("Confirm password").fill("StrongInvite124"); await expect(page.getByText("Passwords match").locator("..")).not.toHaveClass(/is-met/); await expect(submit).toBeDisabled(); await page.screenshot({ path: `${screenshots}/invitation-password-validation.png`, fullPage: true }); await page.getByLabel("Confirm password").fill("StrongInvite123"); await expect(submit).toBeEnabled(); await submit.click(); await expect(page).toHaveURL(/admin-login/); await page.setViewportSize({ width: 390, height: 844 }); const mobile = await invite(request, "mobile"); await page.goto(`/admin-invitation/${mobile.developmentInviteLink.split("/").pop()}`); await page.screenshot({ path: `${screenshots}/invitation-accept-mobile.png`, fullPage: true }); await expect(page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).resolves.toBe(true); await page.goto("/admin-invitation/not-a-valid-token"); await expect(page.getByText("Invitation unavailable")).toBeVisible(); await page.screenshot({ path: `${screenshots}/invitation-invalid.png`, fullPage: true }); });

test("Admin Management uses polished controls and canonical lifecycle actions", async ({ page, request }) => { const pending = await invite(request, "pending"); await authenticate(page, request); await page.setViewportSize({ width: 1440, height: 900 }); await page.goto("/admin/admins"); await expect(page.getByRole("heading", { name: "Admin Management" })).toBeVisible(); await expect(page.getByLabel("Email")).toBeVisible(); await expect(page.getByRole("option", { name: "Support Admin" }).first()).toBeAttached(); await expect(page.getByText(pending.invitation.email)).toBeVisible(); await expect(page.getByRole("button", { name: "Resend" }).first()).toBeVisible(); await expect(page.getByRole("button", { name: "Revoke" }).first()).toBeVisible(); await page.screenshot({ path: `${screenshots}/admin-management-desktop.png`, fullPage: true }); await page.locator(".admin-panel").filter({ hasText: "Invitation Activity" }).screenshot({ path: `${screenshots}/pending-invitations.png` }); await page.setViewportSize({ width: 768, height: 900 }); await page.screenshot({ path: `${screenshots}/admin-management-768.png`, fullPage: true }); await expect(page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).resolves.toBe(true); });

test("revoked security version clears stale admin auth", async ({ page, request }) => { await authenticate(page, request); await page.goto("/admin"); await expect(page).toHaveURL(/\/admin$/); await User.updateOne({ _id: admin._id }, { $inc: { adminSecurityVersion: 1 } }); const rejected = page.waitForResponse((response) => response.url().includes("/admin-auth/me") && response.status() === 401); await page.reload(); await rejected; await expect(page).toHaveURL(/admin-login/); await expect(page.getByRole("heading", { name: "Staff sign in" })).toBeVisible(); await expect(page.evaluate(() => localStorage.getItem("adminToken"))).resolves.toBeNull(); });
