import { useState } from "react";
import { Link, Navigate, useLocation, useNavigate } from "react-router-dom";
import { useAdminAuth } from "../context/AdminAuthContext";
import API from "../services/api";
import "./adminAccess.css";

export default function AdminLogin() {
  const navigate = useNavigate(); const location = useLocation(); const { loginAdmin, adminUser, loading: sessionLoading } = useAdminAuth(); const [form, setForm] = useState({ email: "", password: "" }); const [show, setShow] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  if (!sessionLoading && adminUser) return <Navigate to="/admin" replace />;
  async function submit(event) { event.preventDefault(); if (!form.email.trim() || !form.password) { setError("Enter your email and password."); return; } setLoading(true); setError(""); try { const response = await API.post("/admin-auth/login", form); loginAdmin(response.data.data.token, response.data.data.admin); localStorage.setItem("adminUser", JSON.stringify(response.data.data.admin)); navigate("/admin", { replace: true }); } catch (err) { setError(err.response?.status === 429 ? "Too many sign-in attempts. Please wait and try again." : "Unable to sign in with those credentials."); } finally { setLoading(false); } }
  return <main className="admin-access-page"><section className="admin-access-brand"><Link className="admin-access-logo" to="/"><span>A</span>AuraPay Admin</Link><div className="admin-access-copy"><h1>Secure operations access.</h1><p>Authorized AuraPay staff can monitor Sandbox operations, risk, settlements, and platform activity.</p></div><div className="admin-access-note">Admin access is invitation-only. Activity is audited.</div></section><section className="admin-access-form-panel"><form className="admin-access-card" onSubmit={submit} noValidate><h2>Staff sign in</h2><p>Use your authorized AuraPay administrator account.</p>{location.state?.message && <div className="admin-access-alert admin-access-alert--success" role="status">{location.state.message}</div>}{error && <div className="admin-access-alert" role="alert">{error}</div>}<label className="admin-access-field">Email address<input type="email" autoComplete="username" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} disabled={loading} required /></label><label className="admin-access-field">Password<div className="admin-access-password"><input type={show ? "text" : "password"} autoComplete="current-password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} disabled={loading} required /><button type="button" onClick={() => setShow(!show)} aria-label={show ? "Hide password" : "Show password"}>{show ? "Hide" : "Show"}</button></div></label><button className="admin-access-submit" type="submit" disabled={loading}>{loading ? "Signing in…" : "Sign in"}</button><div className="admin-access-links"><Link to="/admin-forgot-password">Forgot password?</Link><Link to="/">Back to AuraPay</Link></div></form></section></main>;
}
